azureTenant: trygdeetaten.no
kafkaPool: nav-dev
db_tier: db-f1-micro
db_type: POSTGRES_14
db_highAvailability: false
db_pointInTimeRecovery: false
minReplicas: 1
maxReplicas: 1
cpu: 100m
memory: 600Mi
external-host:
  - dokarkiv.dev-fss-pub.nais.io
  - oppgave-q1.dev-fss-pub.nais.io
  - pdl-api.dev-fss-pub.nais.io
  - flex-unleash-api.nav.cloud.nais.io
env:
  SYKEPENGESOKNAD_BACKEND_URL: http://sykepengesoknad-backend
  SYKEPENGESOKNAD_BACKEND_AAD_CLIENT_ID: dev-gcp.flex.sykepengesoknad-backend
  PDL_URL: https://pdl-api.dev-fss-pub.nais.io
  PDL_API_AAD_CLIENT_ID: dev-fss.pdl.pdl-api
  DOKARKIV_URL: https://dokarkiv.dev-fss-pub.nais.io
  DOKARKIV_AAD_CLIENT_ID: dev-fss.teamdokumenthandtering.dokarkiv-q1
  OPPGAVE_URL: https://oppgave-q1.dev-fss-pub.nais.io
  OPPGAVE_AAD_CLIENT_ID: dev-fss.oppgavehandtering.oppgave-q1
  SYKEPENGESOKNAD_KVITTERINGER_URL: http://sykepengesoknad-kvitteringer
  SYKEPENGESOKNAD_KVITTERINGER_AAD_CLIENT_ID: dev-gcp.flex.sykepengesoknad-kvitteringer
  MEDLEMSKAP_VURDERING_URL: http://medlemskap-sykepenger-listener.medlemskap
  MEDLEMSKAP_VURDERING_AAD_CLIENT_ID: dev-gcp.medlemskap.medlemskap-sykepenger-listener
  PDFGEN_URL: http://flex-sykepengesoknad-pdfgen
