apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sykepengesoknad-arkivering-oppgave
  namespace: flex
  labels:
    team: flex
spec:
  image: {{image}}
  strategy:
    type: Recreate
  replicas:
    min: 1
    max: 1
    cpuTresholdPercentage: 90
  port: 8080
  liveness:
    path: /internal/health
  readiness:
    path: /internal/health
  startup:
    path: /internal/health
    initialDelay: 40
  leaderElection: true
  prometheus:
    enabled: true
    path: /internal/prometheus
  resources:
    limits:
      memory: {{memory}}
    requests:
      cpu: {{cpu}}
      memory: {{memory}}
  azure:
    application:
      enabled: true
      tenant: {{azureTenant}}
  kafka:
    pool: {{kafkaPool}}
  gcp:
    sqlInstances:
      - type: POSTGRES_12
        tier: {{db_tier}}
        diskAutoresize: true
        databases:
          - name: sykepengesoknad-arkivering-oppgave-db
            envVarPrefix: DB
            users:
              - name: bigquery-dataprodukt
              - name: bigquery-datastream
        maintenance:
          day: 2
          hour: 2
        flags:
          - name: cloudsql.logical_decoding
            value: "on"
  accessPolicy:
    outbound:
      rules:
        - application: flex-sykepengesoknad-pdfgen
        - application: sykepengesoknad-kvitteringer
        - application: sykepengesoknad-backend
        - application: medlemskap-sykepenger-listener
          namespace: medlemskap
      external:
  {{#each external-host}}
        - host: {{this}}
  {{/each}}
  env:
  {{#each env}}
    - name: {{@key}}
      value: "{{this}}"
  {{/each}}

