azureTenant: nav.no
kafkaPool: nav-prod
db_tier: db-custom-1-3840
db_type: POSTGRES_14
db_highAvailability: true
db_pointInTimeRecovery: true
minReplicas: 1
maxReplicas: 1
cpu: 100m
memory: 900Mi
external-host:
  - dokarkiv.prod-fss-pub.nais.io
  - oppgave.prod-fss-pub.nais.io
  - pdl-api.prod-fss-pub.nais.io
  - flex-unleash-api.nav.cloud.nais.io
env:
  SYKEPENGESOKNAD_BACKEND_URL: http://sykepengesoknad-backend
  SYKEPENGESOKNAD_BACKEND_AAD_CLIENT_ID: prod-gcp.flex.sykepengesoknad-backend
  PDL_URL: https://pdl-api.prod-fss-pub.nais.io
  PDL_API_AAD_CLIENT_ID: prod-fss.pdl.pdl-api
  DOKARKIV_URL: https://dokarkiv.prod-fss-pub.nais.io
  DOKARKIV_AAD_CLIENT_ID: prod-fss.teamdokumenthandtering.dokarkiv
  OPPGAVE_URL: https://oppgave.prod-fss-pub.nais.io
  OPPGAVE_AAD_CLIENT_ID: prod-fss.oppgavehandtering.oppgave
  SYKEPENGESOKNAD_KVITTERINGER_URL: http://sykepengesoknad-kvitteringer
  SYKEPENGESOKNAD_KVITTERINGER_AAD_CLIENT_ID: prod-gcp.flex.sykepengesoknad-kvitteringer
  MEDLEMSKAP_VURDERING_URL: http://medlemskap-sykepenger-listener.medlemskap
  MEDLEMSKAP_VURDERING_AAD_CLIENT_ID: prod-gcp.medlemskap.medlemskap-sykepenger-listener
  PDFGEN_URL: http://flex-sykepengesoknad-pdfgen
