logging.config: classpath:logback.xml

management:
  endpoint.prometheus.enabled: true
  endpoints.web:
    base-path: /internal
    exposure.include: prometheus
    path-mapping.prometheus: /prometheus

KAFKA_TRUSTSTORE_PATH: ""
KAFKA_CREDSTORE_PASSWORD: ""
KAFKA_KEYSTORE_PATH: ""

aiven-kafka:
  auto-offset-reset: none
  security-protocol: SSL

no.nav.security.jwt:
  issuer:
    aad:
      discoveryurl: ${AAD_WELL_KNOWN_URL}
      accepted_audience: ${AAD_SYFOGSAK_CLIENT_ID}
  client:
    registration:
      flex-bucket-uploader-client-credentials:
        token-endpoint-url: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
        grant-type: client_credentials
        scope: api://${FLEX_BUCKET_UPLOADER_AAD_CLIENT_ID}/.default
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-secret: ${AZURE_APP_CLIENT_SECRET}
          client-auth-method: client_secret_basic
      syfosoknad-client-credentials:
        token-endpoint-url: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
        grant-type: client_credentials
        scope: api://${SYFOSOKNAD_AAD_CLIENT_ID}/.default
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-secret: ${AZURE_APP_CLIENT_SECRET}
          client-auth-method: client_secret_basic
      pdl-api-client-credentials:
        token-endpoint-url: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
        grant-type: client_credentials
        scope: api://${PDL_API_AAD_CLIENT_ID}/.default
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-secret: ${AZURE_APP_CLIENT_SECRET}
          client-auth-method: client_secret_basic
      dokarkiv-client-credentials:
        token-endpoint-url: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
        grant-type: client_credentials
        scope: api://${DOKARKIV_AAD_CLIENT_ID}/.default
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-secret: ${AZURE_APP_CLIENT_SECRET}
          client-auth-method: client_secret_basic

spring:
  main.banner-mode: 'off'
  jta.atomikos.datasource:
    max-pool-size: 32
    min-pool-size: 8
  flyway:
    enabled: true

rebehandling.delay.sekunder: 240 # 4 minutter. Må være mindre enn max.poll.interval.ms
pdl.api.url: "http://pdl-api.pdl"
