logging.config: 'classpath:logback-spring.xml'

management:
  endpoints.web:
    base-path: '/internal'
    exposure.include: 'prometheus'
    path-mapping.prometheus: '/prometheus'
  endpoint.prometheus.enabled: true

spring:
  main.banner-mode: off
  jta.atomikos.datasource:
    max-pool-size: 32
    min-pool-size: 8