package no.nav.helse.flex.domain.dto

enum class Soknadstype {
    SELVSTENDIGE_OG_FRILANSERE,
    OPPHOLD_UTLAND,
    ARBEIDSTAKERE,
    ARBEIDSLEDIG,
    BEHANDLINGSDAGER,
    ANNET_ARBEIDSFORHOLD,
    REISETILSKUDD,
    GRADERT_REISETILSKUDD,
}
