apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sykepengesoknad-arkivering-oppgave
  namespace: flex
  labels:
    team: flex
spec:
  image: {{ image }}
  replicas:
    min: 1
    max: 1
    cpuTresholdPercentage: 90
  port: 8080
  liveness:
    path: /internal/health
    initialDelay: 120
    timeout: 1
    periodSeconds: 10
    failureThreshold: 3
  readiness:
    path: /internal/health
    initialDelay: 120
    timeout: 1
  leaderElection: true
  prometheus:
    enabled: true
    path: /internal/prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 768Mi
  azure:
    application:
      enabled: true
      tenant: {{azureTenant}}
  kafka:
    pool: {{kafkaPool}}
  envFrom:
    - secret: sykepengesoknad-arkivering-oppgave-sericeuser
  accessPolicy:
    outbound:
      rules:
        - application: flex-sykepengesoknad-pdfgen
        - application: flex-bucket-uploader
        - application: syfosoknad
          namespace: flex
          cluster: {{environment}}-fss
      external:
      {{#each externalHosts as |url|}}
         - host: {{url}}
      {{/each}}
  env:
    {{#each env}}
      - name: {{@key}}
    value: {{this}}
    {{/each}}

