apiVersion: unleash.nais.io/v1
kind: ApiToken
metadata:
  name: sykepengesoknad-arkivering-oppgave
  namespace: flex
  labels:
    team: flex
spec:
  unleashInstance:
    apiVersion: unleash.nais.io/v1
    kind: RemoteUnleash
    name: flex
  secretName: sykepengesoknad-arkivering-oppgave-unleash-api-token

  # Specify which environment the API token should be created for.
  # Can be one of: development, or production.
  environment: {{unleash-environment}}
