CREATE TABLE INNSENDING (
  INNSENDING_UUID       VARCHAR2(100) NOT NULL PRIMARY KEY ,
  RESSURS_ID            VARCHAR2(100) NOT NULL,
  AKTOR_ID              VARCHAR2(20)  NOT NULL,
  SAKS_ID               VARCHAR2(20)  NOT NULL,
  JOURNALPOST_ID        VARCHAR2(20)  NOT NULL,
  OPPGAVE_ID            VARCHAR2(20)  NOT NULL,
  BEHANDLET             DATE          NOT NULL
);