CREATE TABLE FEILET_INNSENDING (
  INNSENDING_UUID VARCHAR2(100) NOT NULL REFERENCES INNSENDING(INNSENDING_UUID)
);

ALTER TABLE INNSENDING
ALTER COLUMN SAKS_ID VARCHAR2(20) NULL;

ALTER TABLE INNSENDING
ALTER COLUMN JOURNALPOST_ID VARCHAR2(20) NULL;

ALTER TABLE INNSENDING
ALTER COLUMN OPPGAVE_ID VARCHAR2(20) NULL;

ALTER TABLE INNSENDING
ALTER COLUMN BEHANDLET DATE NULL;