CREATE TABLE FEILET_INNSENDING (
  INNSENDING_UUID VARCHAR2(100) NOT NULL REFERENCES INNSENDING(INNSENDING_UUID),
  TIDSPUNKT       DATE          NOT NULL
);

ALTER TABLE INNSENDING MODIFY RESSURS_ID VARCHAR2(100) NULL;
ALTER TABLE INNSENDING MODIFY AKTOR_ID VARCHAR2(20) NULL;
ALTER TABLE INNSENDING MODIFY SAKS_ID VARCHAR2(20) NULL;
ALTER TABLE INNSENDING MODIFY JOURNALPOST_ID VARCHAR2(20) NULL;
ALTER TABLE INNSENDING MODIFY OPPGAVE_ID VARCHAR2(20) NULL;
ALTER TABLE INNSENDING MODIFY BEHANDLET DATE NULL;