DROP INDEX SYKEPENGESOKNAD_ID_INDEX;
DROP TABLE OPPGAVESTYRING;
DROP TABLE OPPGAVESTYRING_LOG;

CREATE TABLE OPPGAVESTYRING_LOG (
    OPPGAVESTYRING_ID   INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    SYKEPENGESOKNAD_ID  VARCHAR2(100) NOT NULL,
    OPPDATERINGSTYPE    VARCHAR2(100) NOT NULL,
    OPPRETTET_DATO      DATE NOT NULL,
    TIMEOUT             TIMESTAMP
);

CREATE TABLE OPPGAVESTYRING (
    SYKEPENGESOKNAD_ID  VARCHAR2(100) NOT NULL PRIMARY KEY,
    TIMEOUT             TIMESTAMP
);

CREATE INDEX SYKEPENGESOKNAD_ID_INDEX ON OPPGAVESTYRING_LOG ( SYKEPENGESOKNAD_ID );
