DROP INDEX SYKEPENGESOKNAD_ID_INDEX;
DROP TABLE OPPGAVESTYRING;
DROP TABLE OPPGAVESTYRING_LOG;

CREATE TABLE OPPGAVESTYRING
(
    SYKEPENGESOKNAD_ID  VARCHAR2(100) NOT NULL PRIMARY KEY,
    STATUS              VARCHAR2(20) NOT NULL,
    OPPRETTET           TIMESTAMP NOT NULL,
    MODIFISERT          TIMESTAMP NOT NULL,
    TIMEOUT             TIMESTAMP
);

CREATE INDEX OPPGAVESTYRING_STATUS ON OPPGAVESTYRING ( STATUS );
